config/routes.rb
Rails.application.routes.draw do

  root to: 'frontend#index'

  get "/establishments/category/:permalink", to: "frontend#search_by_category", as: "search_by_category"

  get "/establishments", to: "frontend#establishments", as: "frontend_establishment"

  get "/establishments/:permalink", to: "frontend#establishment_profile", as: "frontend_establishment_profile"
  
  devise_for :users, skip: [:registration]

  mount InyxContactUsRails::Engine, :at => '', as: 'messages'

  resources :admin, only: [:index]

  scope :admin do
  	resources :users do
  		collection do
	  		post '/delete', to: 'users#delete'
  		end
  	end

    resources :categories do
      collection do
        post '/delete', to: 'categories#delete'
      end
    end

    resources :establishments do
      resources :dishes do
        collection do
            post '/delete', to: 'dishes#delete'
          end
      end
      collection do
        post '/delete', to: 'establishments#delete'
      end
    end


    resources :services do
      collection do
        post '/delete', to: 'services#delete'
      end
    end

    resources :orders, except: [:new, :create, :destroy]

  end


  scope :api do
    #api categories
    get '/categories', to: 'api#categories'

    #api establishments
    get '/establishments', to: 'api#establishments'
    get '/establishments/:permalink', to: 'api#establishment_perfil'
    get '/establishments/:permalink/dishes', to: 'api#dishes_the_establishment'

    #api search
    get '/search', to: 'api#search'

    #api authentication
    post '/authenticate', to: 'authentication#login'
    post '/authenticate/sign_up', to: 'authentication#register'
    delete '/authenticate/sign_out', to: 'authentication#destroy'
    post '/authenticate/forgot-password', to: 'authentication#forgot_password'
    post 'authenticate/password/edit', to: 'authentication#reset_password'

    #api users
    put 'settings/edit', to: 'api_user#edit'
    put 'settings/password', to: 'api_user#edit_password'

    #api orders
    post 'orders/new', to: 'api#create_order'
    get 'orders/:id/canceled', to: "api#canceled_order"
    get 'orders', to: 'api#index_orders'
    get 'orders/:id/pay', to: 'api#pay_order'

    #api mercadopago notifications
    post 'payment/notifications', to: 'api#payment_notifications'
    post 'payment/notifications/ipn', to: 'api#payment_notifications_mp'
  end
  
end

app/models/dish.rb
require 'elasticsearch/model'
class Dish < ActiveRecord::Base	
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks
  has_and_belongs_to_many :categories
  belongs_to :establishment
  before_save :create_permalink
  validates :description, length: { maximum: 220 }
  has_many :items
  has_many :orders, :through => :items
  validates_presence_of :name, :description
  validates_numericality_of :price
  validates_numericality_of :delivery_time, :only_integer => true
  mount_uploader :image, ImageUploader
  

	def as_indexed_json(options={})
    {
      id: self.id.to_s,
      name: self.name,
      description: self.description,
      price: self.price.to_s,
      establishment: self.establishment.name,
      delivery_time: self.delivery_time.to_s,
      categories: self.categories.map { |category| category.name } .join(", ")
    }.as_json
  end

  def create_permalink
    self.permalink=self.name.downcase.parameterize
  end

	def self.query(query)
    { query: { multi_match:  { query: query, fields: [:name, :description, :price, :delivery_time] , operator: :and }  }, sort: { id: "desc" }, size: Dish.count }
  end

  def self.query_frontend(query, sort)
    query = { query: { multi_match:  { query: query, fields: [:name, :description, :price, :delivery_time, :establishment, :categories] , operator: :or }  }, sort: { }, size: Dish.count }
    query[:sort][:price] = sort if !sort.blank? #ordernar pro priceios 'sort' = asc or desc
    query
  end

  def create_permalink
    self.permalink = self.name.downcase.parameterize
  end

  #params[:search] is false
  def self.index(current_user, establishment_id)
    Dish.where(establishment_id: establishment_id).order("created_at DESC")
  end

  #params[:search] is true
  def self.index_search(objects, current_user, establishment_id)
    objects.where(establishment_id: establishment_id).order("created_at DESC")
  end

  #params[:search] is true
  def self.index_total(objects, current_user, establishment_id)
    objects.where(establishment_id: establishment_id).count
  end

  def self.route_index(establishment_id)
    "/admin/establishments/#{establishment_id}/dishes"
  end

  def index_elasticsearch_document
    self.__elasticsearch__.index_document
  end

  def self.multiple_destroy(ids, current_user)
    Dish.destroy ids
  end

end

Dish.import

app/controllers/dishes_controller.rb
class DishesController < ApplicationController
  before_action :set_dish, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!
  layout 'admin/application'
  load_and_authorize_resource
  respond_to :html

  def index
    @establishment = Establishment.find(params[:establishment_id])

    model = params[:controller].classify.constantize;

    if params[:search].blank?
      @objects = model.index(current_user, @establishment.id)
      @total_rows = @objects.count
      @objects = last_page(@objects, params[:currentPage].to_i) if @objects.count != 0
    else
      if(params[:direction]=="refresh")
        sleep(1)
      end
      items = model.search(model.query params[:search])
      @total_rows = model.index_total items.records, current_user, @establishment.id
      @objects = model.index_search last_page_search(items, params[:currentPage].to_i).records, current_user, @establishment.id
    end
    
    respond_to do |format|
      format.html { render action: 'index' }
      format.json { render :json => { objects: @objects, total_rows: @total_rows } }
    end
  end

  def show
  end

  def new
    @dish = Dish.new
  end

  
  def edit
  end


  def create
    @dish = Dish.new(dish_params)

    respond_to do |format|
      if @dish.save
        format.html { redirect_to establishment_dish_path(@dish.establishment_id, @dish.id), notice: 'El plato ha sido creado satisfactoriamente.' }
        format.json { render :show, status: :created, location: @dish }
      else
        format.html { render :new }
        format.json { render json: @dish.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dishes/1
  # PATCH/PUT /dishes/1.json
  def update
    respond_to do |format|
      if @dish.update(dish_params)
        @dish.index_elasticsearch_document
        format.html { redirect_to establishment_dish_path(@dish.establishment_id, @dish.id), notice: 'El plato ha sido actualizado satisfactoriamente.' }
        format.json { render :show, status: :ok, location: @dish }
      else
        format.html { render :edit }
        format.json { render json: @dish.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dishes/1
  # DELETE /dishes/1.json
  def destroy
    @dish.destroy
    respond_to do |format|
      format.html { redirect_to establishment_dishes_path, notice: 'El plato ha sido eliminado satisfactoriamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dish
      @dish = Dish.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dish_params
      params.require(:dish).permit(:name, :description, :price, :delivery_time, :image, :permalink, :establishment_id, {:category_ids => []})
    end
end

app/helpers/dishes_helper.rb
module DishesHelper
end

app/views/dishes/_form.html.haml
- (action_name == "new" or action_name == "create") ? action="create" : action="update"
= simple_form_for @dish, :url => url_for(:action => action, :controller => 'dishes') do |f|
  .container_form
    .title_form
      Datos del plato
    .form-inyx
      = f.input :image, label:false, as: :file, input_html: { class: "file input-inyx", placeholder: 'image', "data-buttonBefore" => false, "data-input" => false, "data-buttonText" => action_name == "new" ? "Subir logo" : "Cambiar logo", id: "input-logo" }
      = f.input :name, label: false, input_html: { class: 'form-control input-inyx', placeholder: "Nombre del plato" }
      = f.input :description, label: false, input_html: { class: 'form-control input-inyx', placeholder: "Descripción del plato"}
      = f.input :price, label: false, as: :float, input_html: { class: 'form-control input-inyx', placeholder: "Precio del plato", min: 0}
      = f.input :delivery_time, label: false, as: :integer, input_html: { class: 'form-control input-inyx', placeholder: "Tiempo estimado en minutos", min: 0}
      %br/
      = f.association :categories, as: :check_boxes, :collection => Category.order(:name), label: "Seleccione categorías a las cual pertenece"
      = f.input :establishment_id, as: :hidden, input_html: { value: params[:establishment_id] }
    .panel-footer
      .form-actions
        = f.button :submit, "Guardar", class: "pull-right btn submit-inyx"
      .clearfix

- if @dish.image.blank?
  :javascript
    $("#input-logo").fileinput({
      browseClass: "btn btn-primary btn-block",
      showCaption: false,
      showRemove: false,
      showUpload: false,
      browseIcon: '<i class="fa fa-folder-open"></i>',
      browseLabel: ' Subir logo',
    });
- else 
  :javascript
    $("#input-logo").fileinput({
      browseClass: "btn btn-primary btn-block",
      showCaption: true,
      captionIcon: '<i class="fa fa-folder-open"></i>',
      showRemove: false,
      showUpload: false,
      browseIcon: '<i class="fa fa-folder-open"></i>',
      browseLabel: ' Cambiar logo',
      initialPreview: ['"#{image_tag @dish.image, class: 'file-preview-image' if !@dish.image.blank?}"'],
      initialCaption: " #{@dish.image.file.filename.humanize}"
    });

app/views/dishes/_view_lg_md.html.haml
%div{ 'ng-init'=>"init(#{@objects.as_json.to_json}, '/admin/establishments/#{@establishment.id}/dishes', '#{params[:search]}', #{@total_rows}, #{Kaminari.config.default_per_page})", "resize" => "" }
  .grid-content
    .col-lg-9.col-md-9{ style: "padding:0px;" } 
      .list-wrapper
        .panel.panel-default
          - flash.each do |name, msg|
            - if msg.is_a?(String)
              %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'} pull-right", id: "message_alerts"}
                %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
                = content_tag :div, msg, :id => "flash_#{name}"
          .panel-heading#list-heading
            = link_to establishments_path, title: "Volver a establecimientos", class: "btn btn-default btn-action" do
              %i.fa.fa-arrow-left
            - if can? :new, Dish
              = link_to new_establishment_dish_path, title: t("admin.buttons.new"), class: "btn btn-default btn-action" do
                %i.fa.fa-plus
            %a.btn.btn-default.btn-action{"ng-click" => "refresh()", "ng-disabled" => "pagesItemsSelected[currentPageServer].length != 0", :title => t("admin.buttons.refresh") }
              %i.fa.fa-refresh#icon-refresh{'ng-show'=>"!loadingRefresh"}
              %i.fa.fa-refresh.fa-spin{'ng-show'=>"loadingRefresh"}
            - if can? :delete, Dish
              %a.btn.btn-default.btn-action{"ng-show" => "objects.length", "ng-click" => "allSelected(objects)", :title => t("admin.buttons.select_all") }
                %i.fa.fa-square-o{"ng-show" => "!btnDelete"}
                %i.fa.fa-check-square-o{ "ng-show" => "btnDelete" } 
              %a.btn.btn-default.btn-action#btn-delete{ "ng-show" => "btnDelete", "ng-click" => "destroy('¿Estas seguro de querer eliminar los usuarios seleccionados?')", :title => t("admin.buttons.trash") }
                %i.fa.fa-circle-o-notch.fa-spin{ 'ng-show' => "loadingDelete" }
                %i.fa.fa-trash-o{ 'ng-show' => "!loadingDelete" }
            .paginator.pull-right{ "ng-show" => "objects.length > 0"}
              %button.btn.btn-default.pull-right.hidden-xs{'disabled'=>"", style:"color:#000; margin-left:3px;"}
                Página {{currentPage+1}} de {{numberOfPages()}}
              %a.btn.btn-default.pull-right.next{ "ng-disabled"=>"currentPage >= total_objects/pageSize - 1 || loadingNext", "ng-click"=>"next()", style: "margin-left:3px" }
                %i.fa.fa-circle-o-notch.fa-spin{ 'ng-show' => "loadingNext" }
                %i.fa.fa-arrow-right{ 'ng-show' => "!loadingNext" }
              %a.btn.btn-default.pull-right.last{'ng-disabled'=>"currentPage == 0 || loadingLast", "ng-click"=>"last()"}
                %i.fa.fa-circle-o-notch.fa-spin{ 'ng-show' => "loadingLast" }
                %i.fa.fa-arrow-left{ 'ng-show' => "!loadingLast" }
          .panel-body{ style: "border-right: 1px solid #e7e7e7;" }
            #table-scroll
              %table.grid{style: "width:100%"}
                %tbody
                  %tr{ class: "select-{{object.checked}}", "ng-click" => "show_object(object)", :id => "row-{{object.id}}", "ng-repeat" => "object in objects | startFrom:currentPage*pageSize | limitTo:pageSize"}
                    - if can? :delete, Dish
                      %td{ width: "1px;" }
                        .checkboxFour
                          %input.checkboxFourInput{:id => "check-{{object.id}}", :type => "checkbox", "ng-model" => "object.checked", "ng-click" => "selected(object); $event.stopPorpagation();" }
                          %label{ for: "check-{{object.id}}" }
                            %span
                    %td {{ object.name }}
                    %td {{ object.price }} Bs.
                    %td {{ object.delivery_time }} minutos.
                  %tr{"ng-show" => "!objects.length"}
                    %td{:style => "width:100%"}
                      %center
                        %i.fa.fa-frown-o
                        No hay platos
      
    .col-lg-3.col-md-3{ style: "padding:0px;"}
      .show-wrapper
        .show-head
        .show-body
          .panel.panel-default
            .panel-heading{ style: "height:55px;" }
              .actions{ "ng-show" => "object_data" }
                .title.pull-left{ style: "margin-top:6px;" }
                  %i.fa.fa-cutlery
                  Plato - {{ object_data.id }}
                - if can? :destroy, Dish
                  = link_to "{{destroy_path(object_data.id)}}", title: t('admin.actions.delete'), :method => :delete, :data => { :confirm => '¿Estas seguro de querer eliminar este usuario?' }, class: "btn btn-default btn-action pull-right", "ng-show" => "object_data" do
                    %i.fa.fa-remove
                - if can? :edit, Dish
                  = link_to "/admin/establishments/#{@establishment.id}/dishes/{{object_data.id}}/edit", title: t('admin.actions.edit'), class: "btn btn-default btn-action pull-right", "ng-show" => "object_data", style: "margin-right:3px;" do
                    %i.fa.fa-pencil
              .actions{ "ng-show" => "!object_data", style: "margin-top:6px;" }
                %i.fa.fa-cutlery
                Menú
            .panel-body
              .data{ style: "height: {{windowHeight-104}}px;" }
                %img{ "ng-show" => "object_data.image", "ng-src" => "{{object_data.image.url}}" }
                .attributes{ "ng-show" => "object_data" }
                  %label Nombre: 
                  {{object_data.name}}
                  %br
                  %label Descripción: 
                  {{object_data.description}}                  
                  %br/
                  %label Precio
                  {{object_data.price}}
                  %br/
                  %label Timepo estiamdo de envio:
                  {{object_data.delivery_time}}
                  %br/
                  %label permalink:
                  {{object_data.permalink}}
                .attributes{ "ng-show" => "!object_data"}
                  %center
                    No se ha seleccionado un plato para mostrar.
        .show-footer
          

app/views/dishes/_view_sm_xs.html.haml
- if can? :new, Dish
	= link_to new_establishment_dish_path, class: "float-button" do
		%i.fa.fa-plus
.panel.panel-default{style:"margin-top:50px"}
	.panel-header
		.paginator{ "ng-show" => "objects.length > 0"}
			%center
				Página {{currentPage+1}} de {{numberOfPages()}}
			%a.btn.btn-default.pull-right.next{ "ng-disabled"=>"currentPage >= total_objects/pageSize - 1 || loadingNext", "ng-click"=>"next()", style: "margin-left:3px" }
				%i.fa.fa-circle-o-notch.fa-spin{ 'ng-show' => "loadingNext" }
				%i.fa.fa-arrow-right{ 'ng-show' => "!loadingNext" }
			%a.btn.btn-default.pull-right.last{'ng-disabled'=>"currentPage == 0 || loadingLast", "ng-click"=>"last()"}
				%i.fa.fa-circle-o-notch.fa-spin{ 'ng-show' => "loadingLast" }
				%i.fa.fa-arrow-left{ 'ng-show' => "!loadingLast" }
	.panel-body#grid{ style: "border-right: 1px solid #e7e7e7;padding-left: 0px;padding-right: 0px;border-top-width: 36px;" }	
		%table.grid{style: "width:100%;"}
			%tbody
				%tr{ class: "select-{{object.checked}}", "ng-click" => "show_object(object)", :id => "row-{{object.id}}", "ng-repeat" => "object in objects | startFrom:currentPage*pageSize | limitTo:pageSize"}
					- if can? :delete, Dish
						%td{ width: "1px;" }
							.checkboxFour
								%input.checkboxFourInput{:id => "check-{{object.id}}", :type => "checkbox", "ng-model" => "object.checked", "ng-click" => "selected(object); $event.stopPorpagation();" }
								%label{ for: "check-{{object.id}}" }
									%span
					%td
						= link_to "{{show_path(object.id)}}", style: "width:100%;" do
							{{ object.name }}
							{{ object.price }}
				%tr{"ng-show" => "!objects.length"}
					%td{:style => "width:100%"}
						%center
							%i.fa.fa-frown-o
							No hay platos.

app/views/dishes/edit.html.haml
= content_for(:title, "Admin - Establecimientos - Dish - Editar")

%div{ style: "padding:10px; padding-bottom:0px;"}
	= render 'form'

app/views/dishes/index.html.haml
= content_for(:title, "Admin - #{@establishment.name} - Menú")

.view-lg-md.hidden-xs.hidden-sm
  = render "view_lg_md"
.view-sm-xs.hidden-lg.hidden-md
  = render "view_sm_xs"

app/views/dishes/new.html.haml
= content_for(:title, "Admin - Establecimientos - Dish - Nuevo")

%div{ style: "padding:10px; padding-bottom:0px;"}
	= render 'form'

app/views/dishes/show.html.haml
= content_for(:title, "Admin - Plato | #{@dish.name}")
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div.hidden-xs{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}", id:"message_alerts"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"
%div
  .panel.panel-default{style:"margin-top:50px"}
    .panel-heading#heading-show{style:"padding-top:5px"}
      .actions
        .title.pull-left{ style: "margin-top:8px;" }
          %i.fa.fa-establishment
          Plato - 
          = @dish.id
        = link_to establishment_dish_path(params[:establishment_id], @dish.id), title: t('admin.actions.delete'), :method => :delete, :data => { :confirm => '¿Estas seguro de querer eliminar este plato?' }, class: "btn btn-default btn-action pull-right" do
          %i.fa.fa-remove
        = link_to edit_establishment_dish_path(params[:establishment_id], @dish.id), title: t('admin.actions.edit'), class: "btn btn-default btn-action pull-right", style: "margin-right:3px;" do
          %i.fa.fa-pencil
        = link_to establishment_dishes_path, title: "Volver a listado de platos", class: "btn btn-default btn-action pull-right", style: "margin-right:3px;" do
          %i.fa.fa-arrow-left
    .panel-body#body-show
      %p
        = image_tag @dish.image, width: "200px;"
      %p
        %b Nombre:
        = @dish.name
      %p
        %b Descripción:
        = @dish.description
      %p
        %b Precio:
        = @dish.price
      %p
        %b Tiempo de entrega:
        = @dish.delivery_time
      %p
        %b Establecimiento:
        = @dish.establishment.name
     