config/routes.rb
Rails.application.routes.draw do

  root to: 'frontend#index'

  get "/establishments/category/:permalink", to: "frontend#search_by_category", as: "search_by_category"

  get "/establishments", to: "frontend#establishments", as: "frontend_establishment"

  get "/establishments/:permalink", to: "frontend#establishment_profile", as: "frontend_establishment_profile"
  
  devise_for :users, skip: [:registration]

  mount InyxContactUsRails::Engine, :at => '', as: 'messages'

  resources :admin, only: [:index]

  scope :admin do
  	resources :users do
  		collection do
	  		post '/delete', to: 'users#delete'
  		end
  	end

    resources :categories do
      collection do
        post '/delete', to: 'categories#delete'
      end
    end

    resources :establishments do
      resources :dishes do
        collection do
            post '/delete', to: 'dishes#delete'
          end
      end
      collection do
        post '/delete', to: 'establishments#delete'
      end
    end


    resources :services do
      collection do
        post '/delete', to: 'services#delete'
      end
    end

    resources :orders, except: [:new, :create, :destroy]

  end


  scope :api do
    #api categories
    get '/categories', to: 'api#categories'

    #api establishments
    get '/establishments', to: 'api#establishments'
    get '/establishments/:permalink', to: 'api#establishment_perfil'
    get '/establishments/:permalink/dishes', to: 'api#dishes_the_establishment'

    #api search
    get '/search', to: 'api#search'

    #api authentication
    post '/authenticate', to: 'authentication#login'
    post '/authenticate/sign_up', to: 'authentication#register'
    delete '/authenticate/sign_out', to: 'authentication#destroy'
    post '/authenticate/forgot-password', to: 'authentication#forgot_password'
    post 'authenticate/password/edit', to: 'authentication#reset_password'

    #api users
    put 'settings/edit', to: 'api_user#edit'
    put 'settings/password', to: 'api_user#edit_password'

    #api orders
    post 'orders/new', to: 'api#create_order'
    get 'orders/:id/canceled', to: "api#canceled_order"
    get 'orders', to: 'api#index_orders'
    get 'orders/:id/pay', to: 'api#pay_order'

    #api mercadopago notifications
    post 'payment/notifications', to: 'api#payment_notifications'
    post 'payment/notifications/ipn', to: 'api#payment_notifications_mp'
  end
  
end

app/models/category.rb
require 'elasticsearch/model'
class Category < ActiveRecord::Base
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks
  has_and_belongs_to_many :establishments
  has_and_belongs_to_many :dishes
	before_save :create_permalink, on: :create
	validates_presence_of :name, :description

	def as_json(options = {})
		{
			id: self.id,
			name: self.name,
			description: self.description,
			permalink: self.permalink
		}
	end

	def self.query(query)
    { query: { multi_match:  { query: query, fields: [:name, :description] , operator: :and }  }, sort: { id: "desc" }, size: Category.count }
  end

  def create_permalink
    self.permalink = self.name.downcase.parameterize
  end

  #params[:search] is false
  def self.index(current_user)
    Category.all.order("created_at DESC")
  end

  #params[:search] is true
  def self.index_search(objects, current_user)
    objects.all.order("created_at DESC")
  end

  #params[:search] is true
  def self.index_total(objects, current_user)
    objects.all.count
  end

  def self.route_index
    "/admin/categories"
  end

  def index_elasticsearch_document
    self.__elasticsearch__.index_document
  end

  def self.multiple_destroy(ids, current_user)
    Category.destroy ids
  end

end

Category.import

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!
  layout 'admin/application'
  load_and_authorize_resource

  respond_to :html

  def show
    respond_with(@category)
  end

  def new
    @category = Category.new
    respond_with(@category)
  end

  def edit
  end

  def create
    @category = Category.new(category_params)
    @category.save
    respond_with(@category)
  end

  def update
    @category.update(category_params)
    @category.index_elasticsearch_document
    respond_with(@category)
  end

  def destroy
    @category.destroy
    respond_with(@category)
  end

  private
    def set_category
      @category = Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:name, :description, :permalink)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.haml
= simple_form_for(@category) do |f|
	.container_form	
		.title_form
			Datos de la categoría
		.form-inyx
			= f.input :name, label:false, input_html: { class: 'form-control input-inyx', placeholder: "Nombre" }
			= f.input :description, label:false, as: :text,input_html: { class: 'form-control input-inyx', placeholder: "Descripción" }
		%br
		.panel-footer
			.form-actions
				= f.button :submit, "Guardar", class: "pull-right btn submit-inyx"
			.clearfix

app/views/categories/_view_lg_md.html.haml
%div{ 'ng-init'=>"init(#{@objects.as_json.to_json}, '/admin/categories', '#{params[:search]}', #{@total_rows}, #{Kaminari.config.default_per_page})", "resize" => "" }
	.grid-content
		.col-lg-9.col-md-9{ style: "padding:0px;" }	
			.list-wrapper
				.panel.panel-default
					- flash.each do |name, msg|
						- if msg.is_a?(String)
							%div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'} pull-right", id: "message_alerts"}
								%button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
								= content_tag :div, msg, :id => "flash_#{name}"
					.panel-heading#list-heading
						- if can? :new, Category
							= link_to new_category_path, title: t("admin.buttons.new"), class: "btn btn-default btn-action" do
								%i.fa.fa-plus
						%a.btn.btn-default.btn-action{"ng-click" => "refresh()", "ng-disabled" => "pagesItemsSelected[currentPageServer].length != 0", :title => t("admin.buttons.refresh") }
							%i.fa.fa-refresh#icon-refresh{'ng-show'=>"!loadingRefresh"}
							%i.fa.fa-refresh.fa-spin{'ng-show'=>"loadingRefresh"}
						- if can? :delete, Category
							%a.btn.btn-default.btn-action{"ng-show" => "objects.length", "ng-click" => "allSelected(objects)", :title => t("admin.buttons.select_all") }
								%i.fa.fa-square-o{"ng-show" => "!btnDelete"}
								%i.fa.fa-check-square-o{ "ng-show" => "btnDelete" }	
							%a.btn.btn-default.btn-action#btn-delete{ "ng-show" => "btnDelete", "ng-click" => "destroy('¿Estas seguro de querer eliminar los usuarios seleccionados?')", :title => t("admin.buttons.trash") }
								%i.fa.fa-circle-o-notch.fa-spin{ 'ng-show' => "loadingDelete" }
								%i.fa.fa-trash-o{ 'ng-show' => "!loadingDelete" }
						.paginator.pull-right{ "ng-show" => "objects.length > 0"}
							%button.btn.btn-default.pull-right.hidden-xs{'disabled'=>"", style:"color:#000; margin-left:3px;"}
								Página {{currentPage+1}} de {{numberOfPages()}}
							%a.btn.btn-default.pull-right.next{ "ng-disabled"=>"currentPage >= total_objects/pageSize - 1 || loadingNext", "ng-click"=>"next()", style: "margin-left:3px" }
								%i.fa.fa-circle-o-notch.fa-spin{ 'ng-show' => "loadingNext" }
								%i.fa.fa-arrow-right{ 'ng-show' => "!loadingNext" }
							%a.btn.btn-default.pull-right.last{'ng-disabled'=>"currentPage == 0 || loadingLast", "ng-click"=>"last()"}
								%i.fa.fa-circle-o-notch.fa-spin{ 'ng-show' => "loadingLast" }
								%i.fa.fa-arrow-left{ 'ng-show' => "!loadingLast" }
					.panel-body{ style: "border-right: 1px solid #e7e7e7;" }
						#table-scroll
							%table.grid{style: "width:100%"}
								%tbody
									%tr{ class: "select-{{object.checked}}", "ng-click" => "show_object(object)", :id => "row-{{object.id}}", "ng-repeat" => "object in objects | startFrom:currentPage*pageSize | limitTo:pageSize"}
										- if can? :delete, Category
											%td{ width: "1px;" }
												.checkboxFour
													%input.checkboxFourInput{:id => "check-{{object.id}}", :type => "checkbox", "ng-model" => "object.checked", "ng-click" => "selected(object); $event.stopPorpagation();" }
													%label{ for: "check-{{object.id}}" }
														%span
										%td {{ object.name }}
										%td {{ object.description }}
									%tr{"ng-show" => "!objects.length"}
										%td{:style => "width:100%"}
											%center
												%i.fa.fa-frown-o
												No hay Categorías.
			
		.col-lg-3.col-md-3{ style: "padding:0px;"}
			.show-wrapper
				.show-head
				.show-body
					.panel.panel-default
						.panel-heading{ style: "height:55px;" }
							.actions{ "ng-show" => "object_data" }
								.title.pull-left{ style: "margin-top:6px;" }
									%i.fa.fa-tags
									Categoría - {{ object_data.id }}
								- if can? :destroy, Category
									= link_to "{{destroy_path(object_data.id)}}", title: t('admin.actions.delete'), :method => :delete, :data => { :confirm => '¿Estas seguro de querer eliminar este usuario?' }, class: "btn btn-default btn-action pull-right", "ng-show" => "object_data" do
										%i.fa.fa-remove
								- if can? :edit, Category
									= link_to "{{edit_path(object_data.id)}}", title: t('admin.actions.edit'), class: "btn btn-default btn-action pull-right", "ng-show" => "object_data", style: "margin-right:3px;" do
										%i.fa.fa-pencil
							.actions{ "ng-show" => "!object_data", style: "margin-top:6px;" }
								%i.fa.fa-tags
								Categoría
						.panel-body
							.data{ style: "height: {{windowHeight-104}}px;" }
								.attributes{ "ng-show" => "object_data" }
									%label Nombre: 
									{{object_data.name}}
									%br
									%label Descripción: 
									{{object_data.description}}
								.attributes{ "ng-show" => "!object_data"}
									%center
										No se ha seleccionado una categoría para mostrar.
				.show-footer

app/views/categories/_view_sm_xs.html.haml
- if can? :new, Category
	= link_to new_category_path, class: "float-button" do
		%i.fa.fa-plus
.panel.panel-default{style:"margin-top:50px"}
	.panel-header
		.paginator{ "ng-show" => "objects.length > 0"}
			%center
				Página {{currentPage+1}} de {{numberOfPages()}}
			%a.btn.btn-default.pull-right.next{ "ng-disabled"=>"currentPage >= total_objects/pageSize - 1 || loadingNext", "ng-click"=>"next()", style: "margin-left:3px" }
				%i.fa.fa-circle-o-notch.fa-spin{ 'ng-show' => "loadingNext" }
				%i.fa.fa-arrow-right{ 'ng-show' => "!loadingNext" }
			%a.btn.btn-default.pull-right.last{'ng-disabled'=>"currentPage == 0 || loadingLast", "ng-click"=>"last()"}
				%i.fa.fa-circle-o-notch.fa-spin{ 'ng-show' => "loadingLast" }
				%i.fa.fa-arrow-left{ 'ng-show' => "!loadingLast" }
	.panel-body#grid{ style: "border-right: 1px solid #e7e7e7;padding-left: 0px;padding-right: 0px;border-top-width: 36px;" }	
		%table.grid{style: "width:100%;"}
			%tbody
				%tr{ class: "select-{{object.checked}}", "ng-click" => "show_object(object)", :id => "row-{{object.id}}", "ng-repeat" => "object in objects | startFrom:currentPage*pageSize | limitTo:pageSize"}
					- if can? :delete, Category
						%td{ width: "1px;" }
							.checkboxFour
								%input.checkboxFourInput{:id => "check-{{object.id}}", :type => "checkbox", "ng-model" => "object.checked", "ng-click" => "selected(object); $event.stopPorpagation();" }
								%label{ for: "check-{{object.id}}" }
									%span
					%td
						= link_to "{{show_path(object.id)}}", style: "width:100%;" do
							{{ object.name }}
				%tr{"ng-show" => "!objects.length"}
					%td{:style => "width:100%"}
						%center
							%i.fa.fa-frown-o
							No hay categorías.

app/views/categories/edit.html.haml
= content_for(:title, "Admin - Restorán | Categoría | Editar")
%div{ style: "padding:10px; padding-bottom:0px;"}
	= render 'form'

app/views/categories/index.html.haml
= content_for(:title, "Admin - Categorías")

.view-lg-md.hidden-xs.hidden-sm
  = render "view_lg_md"
.view-sm-xs.hidden-lg.hidden-md
  = render "view_sm_xs"
          

app/views/categories/new.html.haml
= content_for(:title, "Admin -  Restorán - Categoría - Nuevo")
%div{ style: "padding:10px; padding-bottom:0px;"}
	= render 'form'

app/views/categories/show.html.haml
= content_for(:title, "Admin - Restorán - Categoría - #{@category.name}")
- flash.each do |name, msg|
	- if msg.is_a?(String)
		%div.hidden-xs{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}", id:"message_alerts"}
			%button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
			= content_tag :div, msg, :id => "flash_#{name}"
%div
	.panel.panel-default{style:"margin-top:50px"}
		.panel-heading#heading-show{style:"padding-top:5px"}
			.actions
				.title.pull-left{ style: "margin-top:8px;" }
					%i.fa.fa-user
					Categoría - 
					= @category.id
				- if can? :destroy, Category
					= link_to category_path(@category), title: t('admin.actions.delete'), :method => :delete, :data => { :confirm => '¿Estas seguro de querer eliminar esta categoría?' }, class: "btn btn-default btn-action pull-right" do
						%i.fa.fa-remove
				- if can? :edit, Category
					= link_to  edit_category_path(@category), title: t('admin.actions.edit'), class: "btn btn-default btn-action pull-right", style: "margin-right:3px;" do
						%i.fa.fa-pencil		

		.panel-body#body-show
			%label Nombre:
			= @category.name
			%br/
			%label Descripción:
			= @category.description
			%br/
			