config/routes.rb
Rails.application.routes.draw do

  root to: 'frontend#index'

  get "/establishments/category/:permalink", to: "frontend#search_by_category", as: "search_by_category"

  get "/establishments", to: "frontend#establishments", as: "frontend_establishment"

  get "/establishments/:permalink", to: "frontend#establishment_profile", as: "frontend_establishment_profile"
  
  devise_for :users, skip: [:registration]

  mount InyxContactUsRails::Engine, :at => '', as: 'messages'

  resources :admin, only: [:index]

  scope :admin do
  	resources :users do
  		collection do
	  		post '/delete', to: 'users#delete'
  		end
  	end

    resources :categories do
      collection do
        post '/delete', to: 'categories#delete'
      end
    end

    resources :establishments do
      resources :dishes do
        collection do
            post '/delete', to: 'dishes#delete'
          end
      end
      collection do
        post '/delete', to: 'establishments#delete'
      end
    end


    resources :services do
      collection do
        post '/delete', to: 'services#delete'
      end
    end

    resources :orders, except: [:new, :create, :destroy]

  end


  scope :api do
    #api categories
    get '/categories', to: 'api#categories'

    #api establishments
    get '/establishments', to: 'api#establishments'
    get '/establishments/:permalink', to: 'api#establishment_perfil'
    get '/establishments/:permalink/dishes', to: 'api#dishes_the_establishment'

    #api search
    get '/search', to: 'api#search'

    #api authentication
    post '/authenticate', to: 'authentication#login'
    post '/authenticate/sign_up', to: 'authentication#register'
    delete '/authenticate/sign_out', to: 'authentication#destroy'
    post '/authenticate/forgot-password', to: 'authentication#forgot_password'
    post 'authenticate/password/edit', to: 'authentication#reset_password'

    #api users
    put 'settings/edit', to: 'api_user#edit'
    put 'settings/password', to: 'api_user#edit_password'

    #api orders
    post 'orders/new', to: 'api#create_order'
    get 'orders/:id/canceled', to: "api#canceled_order"
    get 'orders', to: 'api#index_orders'
    get 'orders/:id/pay', to: 'api#pay_order'

    #api mercadopago notifications
    post 'payment/notifications', to: 'api#payment_notifications'
    post 'payment/notifications/ipn', to: 'api#payment_notifications_mp'
  end
  
end

app/models/establishment.rb
require 'elasticsearch/model'
class Establishment < ActiveRecord::Base
	include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks
	has_and_belongs_to_many :categories
	has_and_belongs_to_many :services
  has_many :dishes, :dependent => :destroy
	before_save :create_permalink, on: :create
  validates_presence_of :name, :description, :address, :brand, :banner, :day_aperture, :day_close, :hour_aperture, :hour_close, :city, :state, :country
	validates_uniqueness_of :name, :case_sensitive => false
  validates :phone_1, numericality: { only_integer: true, length: 13 }, :allow_blank => true
  validates :description, length: { maximum: 220 }
  validate :method_payment?, :permit_public_landing?
  mount_uploader :brand, ImageUploader
	mount_uploader :banner, ImageUploader

	def as_json(options = {})
		{
			id: self.id,
			name: self.name,
      brand: self.brand.url,
      banner: self.banner.url,
			description: self.description,
			permalink: self.permalink,
			public: self.public ? "Publicado" : "No publicado",
			address: self.address,
			city: self.city,
			state: self.state,
			country: self.country,
			phone_1: self.phone_1,
      phone_2: self.phone_2,
      credit_card: self.credit_card ? 'Acepta tarjeta de credito' : 'No acepta tarjeta de credito',
      debit: self.debit ? 'Acepta debito' : 'No acepta debito',
      cash: self.cash ? 'Acepta efectivo' : 'No acepta efectivo',
      day_aperture: self.day_aperture,
      day_close: self.day_close,
      longitude: self.longitude,
      latitude: self.latitude,
      hour_aperture: self.hour_aperture,
      hour_close: self.hour_close,
      public_landing: self.public_landing ? 'Publicado en landing' : "No publicado en landing",
      facebook_name: self.facebook_name,
      twitter_name: self.twitter_name,
      instagram_name: self.instagram_name,
      delivery: self.delivery ? 'Aplica delivery' : 'No aplica delivery',
			categories: self.categories.map { |category| category.name } .join(", "),
			services: self.services.map { |category| category.name } .join(", "),
      open: (self.day_open? and self.hour_open?)
    }
	end

	def self.query(query)
    { query: { multi_match:  { query: query, fields: [:name, :description, :city, :state, :country, :categories, :services, :address] , operator: :and }  }, sort: { id: "desc" }, size: Establishment.count }
  end

  def self.query_frontend(query)
    { query: { multi_match:  { query: query, fields: [:name, :description, :city, :state, :country, :categories, :services, :address] , operator: :or }  }, sort: { id: "desc" }, size: Establishment.count }
  end

  def create_permalink
    self.permalink = self.name.downcase.parameterize
  end

  #params[:search] is false
  def self.index(current_user)
    Establishment.all.order("created_at DESC")
  end

  #params[:search] is true
  def self.index_search(objects, current_user)
    objects.all.order("created_at DESC")
  end

  #params[:search] is true
  def self.index_total(objects, current_user)
    objects.all.count
  end

  def self.route_index
    "/admin/establishments"
  end

  def index_elasticsearch_document
    self.__elasticsearch__.index_document
  end

  def self.multiple_destroy(ids, current_user)
    Establishment.destroy ids
  end

  def method_payment?
    errors.add(:base, "Debe seleccionar al menos un metodo de pago.") unless self.credit_card or self.debit or self.cash
  end

  def permit_public_landing?
    errors.add(:public_landing, "El limite de establecimientos publicados en su landing es de 12, no puede publicar este hasta que no desabilite algun otro.") if Establishment.where(public_landing: true).count > 12
  end

  def open
    self.day_open? and self.hour_open?
  end

  def day_open?
    days = { 0 => "Lunes", 1 => "Martes", 2 => "Miercoles", 3 => "Jueves", 4 => "Viernes", 5 => "Sabado", 6 => "Domingo"}
    range_aperture = (days.key(self.day_aperture)..days.key(self.day_close))
    range_aperture.include? Date.today.days_to_week_start
  end

  def hour_open?
    hours = {}
    (1..12).each_with_index { |x, y| hours.merge!({ "#{x}:00 AM" => x != 12 ? y+1 : 0})  } #hash_pm
    (1..12).each_with_index { |x, y| hours.merge!({ "#{x}:00 PM" =>  y+13})  } #hash_am
    range_aperture = (hours[self.hour_aperture]..hours[self.hour_close])

    if range_aperture.include? Time.now.hour and range_aperture.last != Time.now.hour
      true
    elsif range_aperture.include? Time.now.hour and range_aperture.last == Time.now.hour
      false
    end
  end



  settings analysis: {
    :analyzer => {
      :spanish_snowball => {
        :type => "snowball",
        :language => "Spanish",
        :filter => %w{asciifolding lowercase}
      }
    }
  } do
    mapping do
      [:name, :state, :description, :country, :city].each do |attribute|
        indexes attribute, type: 'string', analyzer: 'spanish_snowball'
      end
    end
  end

end

Establishment.__elasticsearch__.create_index! force: true
Establishment.import

app/controllers/establishments_controller.rb
class EstablishmentsController < ApplicationController
  before_action :set_establishment, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!
  layout 'admin/application'
  load_and_authorize_resource
  respond_to :html

  def show
    respond_with(@establishment)
  end

  def new
    @establishment = Establishment.new
  end

  def edit
  end

  def create
    @establishment = Establishment.new(establishment_params)
    @establishment.save
    respond_with(@establishment)
  end

  def update
    @establishment.update(establishment_params)
    @establishment.index_elasticsearch_document
    respond_with(@establishment)
  end

  def destroy
    @establishment.destroy
    respond_with(@establishment)
  end

  private
    def set_establishment
      @establishment = Establishment.find(params[:id])
    end

    def establishment_params
      params.require(:establishment).permit(:brand, :banner, :name, :description, :permalink, :public, :credit_card, :debit, :cash, :address, :city, :state, :country, :phone_1, :phone_2, :facebook_name, :instagram_name, :twitter_name, :latitude, :longitude, :day_aperture, :day_close, :hour_aperture, :hour_close, :public_landing, :delivery, {:category_ids => []}, {:service_ids => []})
    end
end

app/helpers/establishments_helper.rb
module EstablishmentsHelper
end

app/views/establishments/_contact_step.html.haml
.title_form
	Información de contacto
.form-inyx
	= f.input :address, label:false, as: :string, input_html: { class: 'form-control input-inyx', placeholder: "Dirección" }
	= f.input :city, label: false, input_html: { class: 'form-control input-inyx', placeholder: "Ciudad" }
	= f.input :state, label:false, input_html: { class: 'form-control input-inyx', placeholder: "Estado" }
	= f.input :country, label:false, as: :string, input_html: { class: 'form-control input-inyx', placeholder: "País" }
	= f.input :phone_1, label:false, input_html: { class: 'form-control input-inyx', placeholder: "Teléfono primario" }
	= f.input :phone_2, label: false, input_html: { class: 'form-control input-inyx', placeholder: "Teléfono secundario" }
	= f.input :facebook_name, label: false, input_html: { class: 'form-control input-inyx', placeholder: "Nombre en facebook" }
	= f.input :twitter_name, label: false, input_html: { class: 'form-control input-inyx', placeholder: "Nombre en twitter" }
	= f.input :instagram_name, label: false, input_html: { class: 'form-control input-inyx', placeholder: "Nombre en instagram" }
	%label{ style: "margin-top:15px;"} Selecionar la ubicación del establecimiento
	.row
		.col-lg-12
			%script{ src: "http://maps.google.com/maps/api/js?libraries=places&region=uk&language=en&sensor=false" }
			%input#searchTextField.form-control.input-inyx{ type: "text", style: "margin-bottom:10px;", placeholder: "Ingresar locación"}
			#map{ style: 'height: 400px;' }

	= f.input :latitude, as: :hidden
	= f.input :longitude, as: :hidden

:javascript
	$(document).ready(function() { 
		if($("#establishment_latitude").val() != "" && $("#establishment_longitude").val() != "") {
			gmaps_init($("#establishment_latitude").val(), $("#establishment_longitude").val(), 14);
		}
		else {
			gmaps_init(11.7178613, -70.17675500000001, 10);
		}
	});

app/views/establishments/_form.html.haml
= simple_form_for(@establishment) do |f|
	.container_form	
		= render "information_step", f: f
		%br/
		= render "services_step", f: f
		%br/
		= render "contact_step", f: f
		.panel-footer{ style: "margin-bottom: 15px;"}
			.form-actions
				= f.button :submit, "Guardar", class: "pull-right btn submit-inyx"
			.clearfix

- if @establishment.brand.blank?
	:javascript
		$("#input-logo").fileinput({
			browseClass: "btn btn-primary btn-block",
			showCaption: false,
			showRemove: false,
			showUpload: false,
			browseIcon: '<i class="fa fa-folder-open"></i>',
			browseLabel: ' Subir logo',
		});
- else 
	:javascript
		$("#input-logo").fileinput({
			browseClass: "btn btn-primary btn-block",
			showCaption: true,
			captionIcon: '<i class="fa fa-folder-open"></i>',
			showRemove: false,
			showUpload: false,
			browseIcon: '<i class="fa fa-folder-open"></i>',
			browseLabel: ' Cambiar logo',
			initialPreview: ['"#{image_tag @establishment.brand, class: 'file-preview-image' if !@establishment.brand.blank?}"'],
			initialCaption: " #{@establishment.brand.file.filename.humanize}"
		});

- if @establishment.banner.blank?
	:javascript
		$("#input-banner").fileinput({
			browseClass: "btn btn-primary btn-block",
			showCaption: false,
			showRemove: false,
			showUpload: false,
			browseIcon: '<i class="fa fa-folder-open"></i>',
			browseLabel: ' Subir banner',
		});
- else 
	:javascript
		$("#input-banner").fileinput({
			browseClass: "btn btn-primary btn-block",
			showCaption: true,
			captionIcon: '<i class="fa fa-folder-open"></i>',
			showRemove: false,
			showUpload: false,
			browseIcon: '<i class="fa fa-folder-open"></i>',
			browseLabel: ' Cambiar banner',
			initialPreview: ['"#{image_tag @establishment.banner, class: 'file-preview-image' if !@establishment.banner.blank?}"'],
			initialCaption: " #{@establishment.banner.file.filename.humanize}"
		});

app/views/establishments/_services_step.html.haml
.title_form
	Categorías y servicios
.form-inyx
	= f.association :categories, as: :check_boxes, :collection => Category.order(:name), label: "Seleccione categorías a las cual pertenece"
	= f.association :services, as: :check_boxes, :collection => Service.order(:name), label: "Seleccione servicios que ofrecen"
	%br/
	%label Tipo de pagos
	.base-error
		%center
			= "- #{@establishment.errors.messages[:base].first} -" if @establishment.errors.messages[:base]
	.row{ style: "margin-bottom:20px;"}
		.col-md-4
			%center
				%label ¿Acepta tarjeta de credito?
				= f.input :credit_card, label: false, input_html: { style: "margin:0px;" }
		.col-md-4
			%center
				%label ¿Acepta debito?
				= f.input :debit, label: false, input_html: { style: "margin:0px;" }
		.col-md-4
			%center
				%label ¿Acepta efectivo?
				= f.input :cash, label: false, input_html: { style: "margin:0px;" }

app/views/establishments/_view_lg_md.html.haml
%div{ 'ng-init'=>"init(#{@objects.as_json.to_json}, '/admin/establishments', '#{params[:search]}', #{@total_rows}, #{Kaminari.config.default_per_page})", "resize" => "" }
  .grid-content
    .col-lg-9.col-md-9{ style: "padding:0px;" } 
      .list-wrapper
        .panel.panel-default
          - flash.each do |name, msg|
            - if msg.is_a?(String)
              %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'} pull-right", id: "message_alerts"}
                %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
                = content_tag :div, msg, :id => "flash_#{name}"
          .panel-heading#list-heading
            - if can? :new, Establishment
              = link_to new_establishment_path, title: t("admin.buttons.new"), class: "btn btn-default btn-action", data: { no_turbolink: true } do
                %i.fa.fa-plus
            %a.btn.btn-default.btn-action{"ng-click" => "refresh()", "ng-disabled" => "pagesItemsSelected[currentPageServer].length != 0", :title => t("admin.buttons.refresh") }
              %i.fa.fa-refresh#icon-refresh{'ng-show'=>"!loadingRefresh"}
              %i.fa.fa-refresh.fa-spin{'ng-show'=>"loadingRefresh"}
            - if can? :delete, Establishment
              %a.btn.btn-default.btn-action{"ng-show" => "objects.length", "ng-click" => "allSelected(objects)", :title => t("admin.buttons.select_all") }
                %i.fa.fa-square-o{"ng-show" => "!btnDelete"}
                %i.fa.fa-check-square-o{ "ng-show" => "btnDelete" } 
              %a.btn.btn-default.btn-action#btn-delete{ "ng-show" => "btnDelete", "ng-click" => "destroy('¿Estas seguro de querer eliminar los establecimientos seleccionados?')", :title => t("admin.buttons.trash") }
                %i.fa.fa-circle-o-notch.fa-spin{ 'ng-show' => "loadingDelete" }
                %i.fa.fa-trash-o{ 'ng-show' => "!loadingDelete" }
            .paginator.pull-right{ "ng-show" => "objects.length > 0"}
              %button.btn.btn-default.pull-right.hidden-xs{'disabled'=>"", style:"color:#000; margin-left:3px;"}
                Página {{currentPage+1}} de {{numberOfPages()}}
              %a.btn.btn-default.pull-right.next{ "ng-disabled"=>"currentPage >= total_objects/pageSize - 1 || loadingNext", "ng-click"=>"next()", style: "margin-left:3px" }
                %i.fa.fa-circle-o-notch.fa-spin{ 'ng-show' => "loadingNext" }
                %i.fa.fa-arrow-right{ 'ng-show' => "!loadingNext" }
              %a.btn.btn-default.pull-right.last{'ng-disabled'=>"currentPage == 0 || loadingLast", "ng-click"=>"last()"}
                %i.fa.fa-circle-o-notch.fa-spin{ 'ng-show' => "loadingLast" }
                %i.fa.fa-arrow-left{ 'ng-show' => "!loadingLast" }
          .panel-body{ style: "border-right: 1px solid #e7e7e7;" }
            #table-scroll
              %table.grid{style: "width:100%"}
                %tbody
                  %tr{ class: "select-{{object.checked}}", "ng-click" => "show_object(object)", :id => "row-{{object.id}}", "ng-repeat" => "object in objects | startFrom:currentPage*pageSize | limitTo:pageSize"}
                    - if can? :delete, Establishment
                      %td{ width: "1px;" }
                        .checkboxFour
                          %input.checkboxFourInput{:id => "check-{{object.id}}", :type => "checkbox", "ng-model" => "object.checked", "ng-click" => "selected(object); $event.stopPorpagation();" }
                          %label{ for: "check-{{object.id}}" }
                            %span
                    %td {{ object.name }}
                    %td {{ object.city }}
                    %td {{ object.public }}
                    %td {{ object.phone_1 }}
                  %tr{"ng-show" => "!objects.length"}
                    %td{:style => "width:100%"}
                      %center
                        %i.fa.fa-frown-o
                        No hay establecimientos.
      
    .col-lg-3.col-md-3{ style: "padding:0px;"}
      .show-wrapper
        .show-head
        .show-body
          .panel.panel-default
            .panel-heading{ style: "height:55px;" }
              .actions{ "ng-show" => "object_data" }
                .title.pull-left{ style: "margin-top:6px;" }
                  %i.fa.fa-building
                  Establecimiento - {{ object_data.id }}
                - if can? :destroy, Establishment
                  = link_to "{{destroy_path(object_data.id)}}", title: t('admin.actions.delete'), :method => :delete, :data => { :confirm => '¿Estas seguro de querer eliminar este establecimiento?' }, class: "btn btn-default btn-action pull-right", "ng-show" => "object_data" do
                    %i.fa.fa-remove
                - if can? :edit, Establishment
                  = link_to "{{edit_path(object_data.id)}}", title: t('admin.actions.edit'), class: "btn btn-default btn-action pull-right", "ng-show" => "object_data", style: "margin-right:3px;", data: { no_turbolink: true } do
                    %i.fa.fa-pencil
                  = link_to "/admin/establishments/{{object_data.id}}/dishes", title: "Gestionar menú", class: "btn btn-default btn-action pull-right", "ng-show" => "object_data", style: "margin-right:3px;" do
                    %i.fa.fa-cutlery
              .actions{ "ng-show" => "!object_data", style: "margin-top:6px;" }
                %i.fa.fa-building
                Establecimiento
            .panel-body
              .data{ style: "height: {{windowHeight-104}}px;" }
                .attributes{ "ng-show" => "object_data" }
                  %label Nombre: 
                  {{object_data.name}}
                  %br
                  %label Descripción: 
                  {{object_data.description}}                  
                  %br/
                  %label Dirección: 
                  {{object_data.address}}
                  %br
                  %label Ciudad: 
                  {{object_data.city}}
                  %br/
                  %label Estado: 
                  {{object_data.state}}
                  %br
                  %label País: 
                  {{object_data.country}}
                  %br/
                  %label Día de apertura:
                  {{object_data.day_aperture}}
                  %br/
                  %label Día de cierre:
                  {{object_data.day_close}}
                  %br/
                  %label Hora de apertura:
                  {{object_data.hour_aperture}}
                  %br/
                  %label Hora de cierre:
                  {{object_data.hour_close}}
                  %br/
                  %label Teléfono principal:
                  {{object_data.phone_1}}
                  %br/
                  %label{ "ng-if" => "object_data.phone_2" } Teléfono secundario:
                  {{object_data.phone_2}}
                  %br{ "ng-if" => "object_data.phone_2" }
                  %label{ "ng-if" => "object_data.facebook_name" } Facebook:
                  {{object_data.facebook_name}}
                  %br{ "ng-if" => "object_data.facebook_name" }
                  %label{ "ng-if" => "object_data.twitter_name" } Twitter:
                  {{object_data.twitter_name}}
                  %br{ "ng-if" => "object_data.twitter_name" }
                  %label{ "ng-if" => "object_data.instagram_name" } Instagram:
                  {{object_data.instagram_name}}
                  %br{ "ng-if" => "object_data.instagram_name" }
                  %label {{object_data.public}}
                  %br/
                  %label {{object_data.delivery}}
                  %br/
                  %label {{object_data.public_landing}}
                  %br/
                  %label {{object_data.credit_card}}
                  %br/
                  %label {{object_data.debit}}
                  %br/
                  %label {{object_data.credit_card}}
                  #accordion.panel-group{"aria-multiselectable" => "true", :role => "tablist"}
                    .panel.panel-default
                      #headingOne.panel-heading{:role => "tab", style: "background-color:rgb(195, 195, 195);" }
                        %h4.panel-title
                          %a{"aria-controls" => "collapseOne", "aria-expanded" => "true", "data-parent" => "#accordion", "data-toggle" => "collapse", :href => "#collapseOne"}
                            Categorías
                      #collapseOne.panel-collapse.collapse.in{"aria-labelledby" => "headingOne", :role => "tabpanel"}
                        .panel-body{ style: "background-color:rgb(255, 254, 186); padding:10px;" }
                          %label {{object_data.categories}}
                    .panel.panel-default
                      #headingTwo.panel-heading{:role => "tab", style: "background-color:rgb(195, 195, 195);" }
                        %h4.panel-title
                          %a.collapsed{"aria-controls" => "collapseTwo", "aria-expanded" => "false", "data-parent" => "#accordion", "data-toggle" => "collapse", :href => "#collapseTwo"}
                            Servicios
                      #collapseTwo.panel-collapse.collapse{"aria-labelledby" => "headingTwo", :role => "tabpanel"}
                        .panel-body{ style: "background-color:rgb(255, 254, 186); padding:10px;" }
                          %label {{object_data.services}}
                .attributes{ "ng-show" => "!object_data"}
                  %center
                    No se ha seleccionado una categoría para mostrar.
        .show-footer
          

app/views/establishments/_view_sm_xs.html.haml
- if can? :new, Establishment
	= link_to new_establishment_path, class: "float-button" do
		%i.fa.fa-plus
.panel.panel-default{style:"margin-top:50px"}
	.panel-header
		.paginator{ "ng-show" => "objects.length > 0"}
			%center
				Página {{currentPage+1}} de {{numberOfPages()}}
			%a.btn.btn-default.pull-right.next{ "ng-disabled"=>"currentPage >= total_objects/pageSize - 1 || loadingNext", "ng-click"=>"next()", style: "margin-left:3px" }
				%i.fa.fa-circle-o-notch.fa-spin{ 'ng-show' => "loadingNext" }
				%i.fa.fa-arrow-right{ 'ng-show' => "!loadingNext" }
			%a.btn.btn-default.pull-right.last{'ng-disabled'=>"currentPage == 0 || loadingLast", "ng-click"=>"last()"}
				%i.fa.fa-circle-o-notch.fa-spin{ 'ng-show' => "loadingLast" }
				%i.fa.fa-arrow-left{ 'ng-show' => "!loadingLast" }
	.panel-body#grid{ style: "border-right: 1px solid #e7e7e7;padding-left: 0px;padding-right: 0px;border-top-width: 36px;" }	
		%table.grid{style: "width:100%;"}
			%tbody
				%tr{ class: "select-{{object.checked}}", "ng-click" => "show_object(object)", :id => "row-{{object.id}}", "ng-repeat" => "object in objects | startFrom:currentPage*pageSize | limitTo:pageSize"}
					- if can? :delete, Establishment
						%td{ width: "1px;" }
							.checkboxFour
								%input.checkboxFourInput{:id => "check-{{object.id}}", :type => "checkbox", "ng-model" => "object.checked", "ng-click" => "selected(object); $event.stopPorpagation();" }
								%label{ for: "check-{{object.id}}" }
									%span
					%td
						= link_to "{{show_path(object.id)}}", style: "width:100%;" do
							{{ object.name }}
				%tr{"ng-show" => "!objects.length"}
					%td{:style => "width:100%"}
						%center
							%i.fa.fa-frown-o
							No hay establecimientos.

app/views/establishments/edit.html.haml
= content_for(:title, "Admin - Establecimientos | Nuevo")

%div{ style: "padding:10px; padding-bottom:0px;"}
	= render 'form'

app/views/establishments/index.html.haml
= content_for(:title, "Admin - Establecimiento")

.view-lg-md.hidden-xs.hidden-sm
  = render "view_lg_md"
.view-sm-xs.hidden-lg.hidden-md
  = render "view_sm_xs"
          

app/views/establishments/show.html.haml
= content_for(:title, "Admin - Usuarios | #{@establishment.name}")
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div.hidden-xs{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}", id:"message_alerts"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"
%div
  .panel.panel-default{style:"margin-top:50px"}
    .panel-heading#heading-show{style:"padding-top:5px"}
      .actions
        .title.pull-left{ style: "margin-top:8px;" }
          %i.fa.fa-establishment
          Establecimiento - 
          = @establishment.id
        = link_to establishment_path(@establishment), title: t('admin.actions.delete'), :method => :delete, :data => { :confirm => '¿Estas seguro de querer eliminar este establecimiento?' }, class: "btn btn-default btn-action pull-right" do
          %i.fa.fa-remove
        = link_to edit_establishment_path(@establishment), title: t('admin.actions.edit'), class: "btn btn-default btn-action pull-right", style: "margin-right:3px;" do
          %i.fa.fa-pencil 
        = link_to establishment_dishes_path(@establishment), title: "Gestionar menú", class: "btn btn-default btn-action pull-right", style: "margin-right:3px;" do
          %i.fa.fa-cutlery

    .panel-body#body-show
      %p
        = image_tag @establishment.brand, width: "200px;"
      %p
        %b Nombre:
        = @establishment.name
      %p
        %b Descripción:
        = @establishment.description
      %p
        %b Catgorías:
        - @establishment.categories.each do |categorie| 
          = categorie.name+" -"
      %p
        %b Servicios:
        - @establishment.services.each do |service| 
          = service.name+" -"
      %p
        %b Permalink:
        = @establishment.permalink
      %p
        %b ¿Publicado?:
        = @establishment.public ? "Si" : "No"
      %p
        %b Dirección:
        = @establishment.address
      %p
        %b Ciudad:
        = @establishment.city
      %p
        %b Estado:
        = @establishment.state
      %p
        %b País:
        = @establishment.country
      %p
        %b Teléfono primario:
        = @establishment.phone_1
      - unless @establishment.phone_2.blank?  
        %p
          %b Teléfono secundario:
          = @establishment.phone_2
      - unless @establishment.facebook_name.blank?
        %p
          %b Nombre en facebook:
          = @establishment.facebook_name
      - unless @establishment.instagram_name.blank?
        %p
          %b Nombre en instagram:
          = @establishment.instagram_name
      - unless @establishment.twitter_name.blank?
        %p
          %b Nombre en twitter:
          = @establishment.twitter_name
      %p
        %b Latitud:
        = @establishment.latitude
      %p
        %b Longitud:
        = @establishment.longitude